"""新たにLineGroupとLineUserモデルを追加, Eventモデルにline_group_idカラムを追加

Revision ID: 0b3a764910aa
Revises: 9762351c9cf2
Create Date: 2024-11-19 20:09:34.356646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3a764910aa'
down_revision = '9762351c9cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('line_group_id')

    # ### end Alembic commands ###
