"""Eventモデルのline_group_idカラムの型をstringに変更

Revision ID: 4d642be150c7
Revises: 0b3a764910aa
Create Date: 2024-11-28 17:32:28.938222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d642be150c7'
down_revision = '0b3a764910aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_group_id', sa.String(length=64), nullable=False),
    sa.Column('line_group_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_groups_line_group_id'), ['line_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_groups_line_group_name'), ['line_group_name'], unique=False)

    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('line_user_name', sa.String(length=64), nullable=False),
    sa.Column('line_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_group_id'], ['line_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_users_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_users_line_user_name'), ['line_user_name'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('line_group_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('line_group_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('line_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_users_line_user_name'))
        batch_op.drop_index(batch_op.f('ix_line_users_line_user_id'))

    op.drop_table('line_users')
    with op.batch_alter_table('line_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_groups_line_group_name'))
        batch_op.drop_index(batch_op.f('ix_line_groups_line_group_id'))

    op.drop_table('line_groups')
    # ### end Alembic commands ###
