"""Userモデルにline_user_idカラムを追加

Revision ID: 57454b96e8c8
Revises: 4d642be150c7
Create Date: 2024-11-28 18:01:01.752117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57454b96e8c8'
down_revision = '4d642be150c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['line_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###
