"""delete password and email columns on users and add line token column on users

Revision ID: 9762351c9cf2
Revises: 49e6bc32f23c
Create Date: 2024-11-14 17:22:01.237860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9762351c9cf2'
down_revision = '49e6bc32f23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_token', sa.String(length=128), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('_password')
        batch_op.drop_column('line_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_id', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('_password', sa.VARCHAR(length=512), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('line_token')

    # ### end Alembic commands ###
